# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.claim_api import ClaimApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClaimApi(unittest.TestCase):
    """ClaimApi unit test stubs"""

    def setUp(self):
        self.api = ClaimApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_claim_post_submission_post(self):
        """Test case for api_claim_post_submission_post

        Upload submission transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
