# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.erx_api import ERXApi  # noqa: E501
from swagger_client.rest import ApiException


class TestERXApi(unittest.TestCase):
    """ERXApi unit test stubs"""

    def setUp(self):
        self.api = ERXApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_erx_check_activity_status_get(self):
        """Test case for api_erx_check_activity_status_get

        Check prescription activity status  # noqa: E501
        """
        pass

    def test_api_erx_get_new_get(self):
        """Test case for api_erx_get_new_get

        Get New Transactions  # noqa: E501
        """
        pass

    def test_api_erx_patient_prescriptions_get(self):
        """Test case for api_erx_patient_prescriptions_get

        View Patient Prescriptions.  # noqa: E501
        """
        pass

    def test_api_erx_post_request_post(self):
        """Test case for api_erx_post_request_post

        Upload Erx Request transaction  # noqa: E501
        """
        pass

    def test_api_erx_search_get(self):
        """Test case for api_erx_search_get

        Search ERX Transactions  # noqa: E501
        """
        pass

    def test_api_erx_set_downloaded_post(self):
        """Test case for api_erx_set_downloaded_post

        Set transaction as downloaded  # noqa: E501
        """
        pass

    def test_api_erx_view_get(self):
        """Test case for api_erx_view_get

        download the ERX transaction  # noqa: E501
        """
        pass

    def test_api_erx_view_pharmacy_prescription_get(self):
        """Test case for api_erx_view_pharmacy_prescription_get

        View Prescription (Pharmacy Use only)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
