# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tpo_data_models_shared_search_item import TpoDataModelsSharedSearchItem  # noqa: E501
from swagger_client.rest import ApiException


class TestTpoDataModelsSharedSearchItem(unittest.TestCase):
    """TpoDataModelsSharedSearchItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTpoDataModelsSharedSearchItem(self):
        """Test TpoDataModelsSharedSearchItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tpo_data_models_shared_search_item.TpoDataModelsSharedSearchItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
