# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tpo_data_dt_os_lab_encounter_dto import TpoDataDTOsLabEncounterDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestTpoDataDTOsLabEncounterDTO(unittest.TestCase):
    """TpoDataDTOsLabEncounterDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTpoDataDTOsLabEncounterDTO(self):
        """Test TpoDataDTOsLabEncounterDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tpo_data_dt_os_lab_encounter_dto.TpoDataDTOsLabEncounterDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
