# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.authorization_api import AuthorizationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthorizationApi(unittest.TestCase):
    """AuthorizationApi unit test stubs"""

    def setUp(self):
        self.api = AuthorizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_authorization_get_new_get(self):
        """Test case for api_authorization_get_new_get

        Get New Transactions  # noqa: E501
        """
        pass

    def test_api_authorization_post_request_post(self):
        """Test case for api_authorization_post_request_post

        Upload Prior Request transaction  # noqa: E501
        """
        pass

    def test_api_authorization_search_get(self):
        """Test case for api_authorization_search_get

        Search Authorization Transactions  # noqa: E501
        """
        pass

    def test_api_authorization_set_downloaded_post(self):
        """Test case for api_authorization_set_downloaded_post

        Set transaction as downloaded  # noqa: E501
        """
        pass

    def test_api_authorization_view_get(self):
        """Test case for api_authorization_view_get

        View the Authorization transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
