# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tpo_shared_entities_error import TpoSharedEntitiesError  # noqa: E501
from swagger_client.rest import ApiException


class TestTpoSharedEntitiesError(unittest.TestCase):
    """TpoSharedEntitiesError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTpoSharedEntitiesError(self):
        """Test TpoSharedEntitiesError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tpo_shared_entities_error.TpoSharedEntitiesError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
