# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tpo_data_dt_os_erxe_rx_request_dto import TpoDataDTOsERXERxRequestDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestTpoDataDTOsERXERxRequestDTO(unittest.TestCase):
    """TpoDataDTOsERXERxRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTpoDataDTOsERXERxRequestDTO(self):
        """Test TpoDataDTOsERXERxRequestDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tpo_data_dt_os_erxe_rx_request_dto.TpoDataDTOsERXERxRequestDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
