# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tpo_data_models_erx_prescription_activity_status import TpoDataModelsERXPrescriptionActivityStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestTpoDataModelsERXPrescriptionActivityStatus(unittest.TestCase):
    """TpoDataModelsERXPrescriptionActivityStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTpoDataModelsERXPrescriptionActivityStatus(self):
        """Test TpoDataModelsERXPrescriptionActivityStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tpo_data_models_erx_prescription_activity_status.TpoDataModelsERXPrescriptionActivityStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
