# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataDTOsClaimResubmissionDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attachment': 'str',
        'comment': 'str',
        'type': 'str'
    }

    attribute_map = {
        'attachment': 'attachment',
        'comment': 'comment',
        'type': 'type'
    }

    def __init__(self, attachment=None, comment=None, type=None):  # noqa: E501
        """TpoDataDTOsClaimResubmissionDTO - a model defined in Swagger"""  # noqa: E501
        self._attachment = None
        self._comment = None
        self._type = None
        self.discriminator = None
        if attachment is not None:
            self.attachment = attachment
        self.comment = comment
        self.type = type

    @property
    def attachment(self):
        """Gets the attachment of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501

        Gets or sets the attachment.  # noqa: E501

        :return: The attachment of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501
        :rtype: str
        """
        return self._attachment

    @attachment.setter
    def attachment(self, attachment):
        """Sets the attachment of this TpoDataDTOsClaimResubmissionDTO.

        Gets or sets the attachment.  # noqa: E501

        :param attachment: The attachment of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501
        :type: str
        """

        self._attachment = attachment

    @property
    def comment(self):
        """Gets the comment of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501

        Gets or sets the comment.  # noqa: E501

        :return: The comment of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this TpoDataDTOsClaimResubmissionDTO.

        Gets or sets the comment.  # noqa: E501

        :param comment: The comment of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501
        :type: str
        """
        if comment is None:
            raise ValueError("Invalid value for `comment`, must not be `None`")  # noqa: E501

        self._comment = comment

    @property
    def type(self):
        """Gets the type of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501

        Gets or sets the type.  # noqa: E501

        :return: The type of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TpoDataDTOsClaimResubmissionDTO.

        Gets or sets the type.  # noqa: E501

        :param type: The type of this TpoDataDTOsClaimResubmissionDTO.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataDTOsClaimResubmissionDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataDTOsClaimResubmissionDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
