# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataDTOsControllerParametersRadRequestParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rad_request': 'TpoDataDTOsRadRadRequestDTO'
    }

    attribute_map = {
        'rad_request': 'RadRequest'
    }

    def __init__(self, rad_request=None):  # noqa: E501
        """TpoDataDTOsControllerParametersRadRequestParameter - a model defined in Swagger"""  # noqa: E501
        self._rad_request = None
        self.discriminator = None
        self.rad_request = rad_request

    @property
    def rad_request(self):
        """Gets the rad_request of this TpoDataDTOsControllerParametersRadRequestParameter.  # noqa: E501


        :return: The rad_request of this TpoDataDTOsControllerParametersRadRequestParameter.  # noqa: E501
        :rtype: TpoDataDTOsRadRadRequestDTO
        """
        return self._rad_request

    @rad_request.setter
    def rad_request(self, rad_request):
        """Sets the rad_request of this TpoDataDTOsControllerParametersRadRequestParameter.


        :param rad_request: The rad_request of this TpoDataDTOsControllerParametersRadRequestParameter.  # noqa: E501
        :type: TpoDataDTOsRadRadRequestDTO
        """
        if rad_request is None:
            raise ValueError("Invalid value for `rad_request`, must not be `None`")  # noqa: E501

        self._rad_request = rad_request

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataDTOsControllerParametersRadRequestParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataDTOsControllerParametersRadRequestParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
