# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataDTOsControllerParametersErxRequestParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'erx_request': 'TpoDataDTOsERXERxRequestDTO'
    }

    attribute_map = {
        'erx_request': 'ErxRequest'
    }

    def __init__(self, erx_request=None):  # noqa: E501
        """TpoDataDTOsControllerParametersErxRequestParameter - a model defined in Swagger"""  # noqa: E501
        self._erx_request = None
        self.discriminator = None
        self.erx_request = erx_request

    @property
    def erx_request(self):
        """Gets the erx_request of this TpoDataDTOsControllerParametersErxRequestParameter.  # noqa: E501


        :return: The erx_request of this TpoDataDTOsControllerParametersErxRequestParameter.  # noqa: E501
        :rtype: TpoDataDTOsERXERxRequestDTO
        """
        return self._erx_request

    @erx_request.setter
    def erx_request(self, erx_request):
        """Sets the erx_request of this TpoDataDTOsControllerParametersErxRequestParameter.


        :param erx_request: The erx_request of this TpoDataDTOsControllerParametersErxRequestParameter.  # noqa: E501
        :type: TpoDataDTOsERXERxRequestDTO
        """
        if erx_request is None:
            raise ValueError("Invalid value for `erx_request`, must not be `None`")  # noqa: E501

        self._erx_request = erx_request

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataDTOsControllerParametersErxRequestParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataDTOsControllerParametersErxRequestParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
