# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataModelsSharedActivityStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'activity_id': 'str',
        'status': 'str',
        'activity_code': 'str',
        'activity_description': 'str',
        'dispense_date': 'str'
    }

    attribute_map = {
        'activity_id': 'ActivityID',
        'status': 'Status',
        'activity_code': 'ActivityCode',
        'activity_description': 'ActivityDescription',
        'dispense_date': 'DispenseDate'
    }

    def __init__(self, activity_id=None, status=None, activity_code=None, activity_description=None,
                 dispense_date=None):  # noqa: E501
        """TpoDataModelsSharedActivityStatus - a model defined in Swagger"""  # noqa: E501
        self._activity_id = None
        self._status = None
        self._activity_code = None
        self._activity_description = None
        self._dispense_date = None
        self.discriminator = None
        if activity_id is not None:
            self.activity_id = activity_id
        if status is not None:
            self.status = status
        if activity_code is not None:
            self.activity_code = activity_code
        if activity_description is not None:
            self.activity_description = activity_description
        if dispense_date is not None:
            self.dispense_date = dispense_date

    @property
    def activity_id(self):
        """Gets the activity_id of this TpoDataModelsSharedActivityStatus.  # noqa: E501


        :return: The activity_id of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :rtype: str
        """
        return self._activity_id

    @activity_id.setter
    def activity_id(self, activity_id):
        """Sets the activity_id of this TpoDataModelsSharedActivityStatus.


        :param activity_id: The activity_id of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :type: str
        """

        self._activity_id = activity_id

    @property
    def status(self):
        """Gets the status of this TpoDataModelsSharedActivityStatus.  # noqa: E501


        :return: The status of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TpoDataModelsSharedActivityStatus.


        :param status: The status of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def activity_code(self):
        """Gets the activity_code of this TpoDataModelsSharedActivityStatus.  # noqa: E501


        :return: The activity_code of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :rtype: str
        """
        return self._activity_code

    @activity_code.setter
    def activity_code(self, activity_code):
        """Sets the activity_code of this TpoDataModelsSharedActivityStatus.


        :param activity_code: The activity_code of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :type: str
        """

        self._activity_code = activity_code

    @property
    def activity_description(self):
        """Gets the activity_description of this TpoDataModelsSharedActivityStatus.  # noqa: E501


        :return: The activity_description of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :rtype: str
        """
        return self._activity_description

    @activity_description.setter
    def activity_description(self, activity_description):
        """Sets the activity_description of this TpoDataModelsSharedActivityStatus.


        :param activity_description: The activity_description of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :type: str
        """

        self._activity_description = activity_description

    @property
    def dispense_date(self):
        """Gets the dispense_date of this TpoDataModelsSharedActivityStatus.  # noqa: E501


        :return: The dispense_date of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :rtype: str
        """
        return self._dispense_date

    @dispense_date.setter
    def dispense_date(self, dispense_date):
        """Sets the dispense_date of this TpoDataModelsSharedActivityStatus.


        :param dispense_date: The dispense_date of this TpoDataModelsSharedActivityStatus.  # noqa: E501
        :type: str
        """

        self._dispense_date = dispense_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataModelsSharedActivityStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataModelsSharedActivityStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
