# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataDTOsSharedObservationDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'code': 'str',
        'value': 'str',
        'value_type': 'str'
    }

    attribute_map = {
        'type': 'Type',
        'code': 'Code',
        'value': 'Value',
        'value_type': 'ValueType'
    }

    def __init__(self, type=None, code=None, value=None, value_type=None):  # noqa: E501
        """TpoDataDTOsSharedObservationDTO - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._code = None
        self._value = None
        self._value_type = None
        self.discriminator = None
        self.type = type
        self.code = code
        if value is not None:
            self.value = value
        if value_type is not None:
            self.value_type = value_type

    @property
    def type(self):
        """Gets the type of this TpoDataDTOsSharedObservationDTO.  # noqa: E501

        The type of the observation:  • LOINC  • Text  • File  • Universal Dental  • Financial  • Grouping  • ERX  • Result  • Excluded from DRG  • Duration  • Instructions  # noqa: E501

        :return: The type of this TpoDataDTOsSharedObservationDTO.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TpoDataDTOsSharedObservationDTO.

        The type of the observation:  • LOINC  • Text  • File  • Universal Dental  • Financial  • Grouping  • ERX  • Result  • Excluded from DRG  • Duration  • Instructions  # noqa: E501

        :param type: The type of this TpoDataDTOsSharedObservationDTO.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def code(self):
        """Gets the code of this TpoDataDTOsSharedObservationDTO.  # noqa: E501

        The code describing the Observation value.  # noqa: E501

        :return: The code of this TpoDataDTOsSharedObservationDTO.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this TpoDataDTOsSharedObservationDTO.

        The code describing the Observation value.  # noqa: E501

        :param code: The code of this TpoDataDTOsSharedObservationDTO.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def value(self):
        """Gets the value of this TpoDataDTOsSharedObservationDTO.  # noqa: E501

        The observed value of the Activity.  # noqa: E501

        :return: The value of this TpoDataDTOsSharedObservationDTO.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this TpoDataDTOsSharedObservationDTO.

        The observed value of the Activity.  # noqa: E501

        :param value: The value of this TpoDataDTOsSharedObservationDTO.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def value_type(self):
        """Gets the value_type of this TpoDataDTOsSharedObservationDTO.  # noqa: E501

        Unit of measure for the Observation Value.  # noqa: E501

        :return: The value_type of this TpoDataDTOsSharedObservationDTO.  # noqa: E501
        :rtype: str
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type):
        """Sets the value_type of this TpoDataDTOsSharedObservationDTO.

        Unit of measure for the Observation Value.  # noqa: E501

        :param value_type: The value_type of this TpoDataDTOsSharedObservationDTO.  # noqa: E501
        :type: str
        """

        self._value_type = value_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataDTOsSharedObservationDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataDTOsSharedObservationDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
