# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataDTOsAuthorizationRequestEncounterDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'facility_id': 'str',
        'type': 'int'
    }

    attribute_map = {
        'facility_id': 'FacilityID',
        'type': 'Type'
    }

    def __init__(self, facility_id=None, type=None):  # noqa: E501
        """TpoDataDTOsAuthorizationRequestEncounterDTO - a model defined in Swagger"""  # noqa: E501
        self._facility_id = None
        self._type = None
        self.discriminator = None
        self.facility_id = facility_id
        self.type = type

    @property
    def facility_id(self):
        """Gets the facility_id of this TpoDataDTOsAuthorizationRequestEncounterDTO.  # noqa: E501

        ID  of the facility responsible for the Encounter  # noqa: E501

        :return: The facility_id of this TpoDataDTOsAuthorizationRequestEncounterDTO.  # noqa: E501
        :rtype: str
        """
        return self._facility_id

    @facility_id.setter
    def facility_id(self, facility_id):
        """Sets the facility_id of this TpoDataDTOsAuthorizationRequestEncounterDTO.

        ID  of the facility responsible for the Encounter  # noqa: E501

        :param facility_id: The facility_id of this TpoDataDTOsAuthorizationRequestEncounterDTO.  # noqa: E501
        :type: str
        """
        if facility_id is None:
            raise ValueError("Invalid value for `facility_id`, must not be `None`")  # noqa: E501

        self._facility_id = facility_id

    @property
    def type(self):
        """Gets the type of this TpoDataDTOsAuthorizationRequestEncounterDTO.  # noqa: E501

        Type of the encounter: check from the portal  1 = No Bed + No emergency room  2 = No Bed + Emergency room  3 = Inpatient Bed + No emergency room  4 = Inpatient Bed + Emergency room  5 = Daycase Bed + No emergency room  6 = Daycase Bed + Emergency room  7 = Nationals Screening  8 = New Visa Screening  9 = Renewal Visa Screening  12 = Home  13 = Assisted Living Facility  15 = Mobile Unit  41 = Ambulance - Land  42 = Ambulance - Air or Water  # noqa: E501

        :return: The type of this TpoDataDTOsAuthorizationRequestEncounterDTO.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TpoDataDTOsAuthorizationRequestEncounterDTO.

        Type of the encounter: check from the portal  1 = No Bed + No emergency room  2 = No Bed + Emergency room  3 = Inpatient Bed + No emergency room  4 = Inpatient Bed + Emergency room  5 = Daycase Bed + No emergency room  6 = Daycase Bed + Emergency room  7 = Nationals Screening  8 = New Visa Screening  9 = Renewal Visa Screening  12 = Home  13 = Assisted Living Facility  15 = Mobile Unit  41 = Ambulance - Land  42 = Ambulance - Air or Water  # noqa: E501

        :param type: The type of this TpoDataDTOsAuthorizationRequestEncounterDTO.  # noqa: E501
        :type: int
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataDTOsAuthorizationRequestEncounterDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataDTOsAuthorizationRequestEncounterDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
