# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataDTOsClaimSubmissionDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'header': 'TpoDataDTOsSharedSubmissionHeaderDTO',
        'claim': 'list[TpoDataDTOsClaimClaimDTO]'
    }

    attribute_map = {
        'header': 'Header',
        'claim': 'Claim'
    }

    def __init__(self, header=None, claim=None):  # noqa: E501
        """TpoDataDTOsClaimSubmissionDTO - a model defined in Swagger"""  # noqa: E501
        self._header = None
        self._claim = None
        self.discriminator = None
        self.header = header
        if claim is not None:
            self.claim = claim

    @property
    def header(self):
        """Gets the header of this TpoDataDTOsClaimSubmissionDTO.  # noqa: E501


        :return: The header of this TpoDataDTOsClaimSubmissionDTO.  # noqa: E501
        :rtype: TpoDataDTOsSharedSubmissionHeaderDTO
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this TpoDataDTOsClaimSubmissionDTO.


        :param header: The header of this TpoDataDTOsClaimSubmissionDTO.  # noqa: E501
        :type: TpoDataDTOsSharedSubmissionHeaderDTO
        """
        if header is None:
            raise ValueError("Invalid value for `header`, must not be `None`")  # noqa: E501

        self._header = header

    @property
    def claim(self):
        """Gets the claim of this TpoDataDTOsClaimSubmissionDTO.  # noqa: E501

        List of Claims.  # noqa: E501

        :return: The claim of this TpoDataDTOsClaimSubmissionDTO.  # noqa: E501
        :rtype: list[TpoDataDTOsClaimClaimDTO]
        """
        return self._claim

    @claim.setter
    def claim(self, claim):
        """Sets the claim of this TpoDataDTOsClaimSubmissionDTO.

        List of Claims.  # noqa: E501

        :param claim: The claim of this TpoDataDTOsClaimSubmissionDTO.  # noqa: E501
        :type: list[TpoDataDTOsClaimClaimDTO]
        """

        self._claim = claim

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataDTOsClaimSubmissionDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataDTOsClaimSubmissionDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
