# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataDTOsClaimActivityDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'start': 'str',
        'type': 'str',
        'alternative_reason': 'str',
        'code': 'str',
        'quantity': 'float',
        'net': 'float',
        'clinician': 'str',
        'prior_authorization_id': 'str',
        'dispensed_activity_id': 'str',
        'observation': 'list[TpoDataDTOsSharedObservationDTO]',
        'result': 'list[TpoDataDTOsClaimActivityResultDTO]'
    }

    attribute_map = {
        'id': 'ID',
        'start': 'Start',
        'type': 'Type',
        'alternative_reason': 'AlternativeReason',
        'code': 'Code',
        'quantity': 'Quantity',
        'net': 'Net',
        'clinician': 'Clinician',
        'prior_authorization_id': 'PriorAuthorizationID',
        'dispensed_activity_id': 'DispensedActivityID',
        'observation': 'Observation',
        'result': 'Result'
    }

    def __init__(self, id=None, start=None, type=None, alternative_reason=None, code=None, quantity=None, net=None,
                 clinician=None, prior_authorization_id=None, dispensed_activity_id=None, observation=None,
                 result=None):  # noqa: E501
        """TpoDataDTOsClaimActivityDTO - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._start = None
        self._type = None
        self._alternative_reason = None
        self._code = None
        self._quantity = None
        self._net = None
        self._clinician = None
        self._prior_authorization_id = None
        self._dispensed_activity_id = None
        self._observation = None
        self._result = None
        self.discriminator = None
        self.id = id
        self.start = start
        self.type = type
        if alternative_reason is not None:
            self.alternative_reason = alternative_reason
        self.code = code
        self.quantity = quantity
        self.net = net
        self.clinician = clinician
        if prior_authorization_id is not None:
            self.prior_authorization_id = prior_authorization_id
        if dispensed_activity_id is not None:
            self.dispensed_activity_id = dispensed_activity_id
        if observation is not None:
            self.observation = observation
        if result is not None:
            self.result = result

    @property
    def id(self):
        """Gets the id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        Unique identifier of activity within a claim.  # noqa: E501

        :return: The id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TpoDataDTOsClaimActivityDTO.

        Unique identifier of activity within a claim.  # noqa: E501

        :param id: The id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def start(self):
        """Gets the start of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        The date and time at which Activity started              Date Time format: DD/MM/YYYYY HH:MM.  # noqa: E501

        :return: The start of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: str
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this TpoDataDTOsClaimActivityDTO.

        The date and time at which Activity started              Date Time format: DD/MM/YYYYY HH:MM.  # noqa: E501

        :param start: The start of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: str
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def type(self):
        """Gets the type of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        The type of activity. 3 = CPT; 4 = HCPCS; 5 = Drug; 6 = Dental; 8 = Service Code; 9 = DRG; 10 = Scientific Code.  # noqa: E501

        :return: The type of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TpoDataDTOsClaimActivityDTO.

        The type of activity. 3 = CPT; 4 = HCPCS; 5 = Drug; 6 = Dental; 8 = Service Code; 9 = DRG; 10 = Scientific Code.  # noqa: E501

        :param type: The type of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def alternative_reason(self):
        """Gets the alternative_reason of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        The reason for alternative dispensing.  # noqa: E501

        :return: The alternative_reason of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: str
        """
        return self._alternative_reason

    @alternative_reason.setter
    def alternative_reason(self, alternative_reason):
        """Sets the alternative_reason of this TpoDataDTOsClaimActivityDTO.

        The reason for alternative dispensing.  # noqa: E501

        :param alternative_reason: The alternative_reason of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: str
        """

        self._alternative_reason = alternative_reason

    @property
    def code(self):
        """Gets the code of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        ActivityCode is the code, specified by ActivityType, for the Activity performed.  # noqa: E501

        :return: The code of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this TpoDataDTOsClaimActivityDTO.

        ActivityCode is the code, specified by ActivityType, for the Activity performed.  # noqa: E501

        :param code: The code of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        Identifies the number of units (quantity) for a specific Activity.  # noqa: E501

        :return: The quantity of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this TpoDataDTOsClaimActivityDTO.

        Identifies the number of units (quantity) for a specific Activity.  # noqa: E501

        :param quantity: The quantity of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: float
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def net(self):
        """Gets the net of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        The net charges billed by the provider to the Payer for this Activity.  # noqa: E501

        :return: The net of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: float
        """
        return self._net

    @net.setter
    def net(self, net):
        """Sets the net of this TpoDataDTOsClaimActivityDTO.

        The net charges billed by the provider to the Payer for this Activity.  # noqa: E501

        :param net: The net of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: float
        """
        if net is None:
            raise ValueError("Invalid value for `net`, must not be `None`")  # noqa: E501

        self._net = net

    @property
    def clinician(self):
        """Gets the clinician of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        License number of the Clinician who is providing the treatment or care for the patient.  # noqa: E501

        :return: The clinician of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: str
        """
        return self._clinician

    @clinician.setter
    def clinician(self, clinician):
        """Sets the clinician of this TpoDataDTOsClaimActivityDTO.

        License number of the Clinician who is providing the treatment or care for the patient.  # noqa: E501

        :param clinician: The clinician of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: str
        """
        if clinician is None:
            raise ValueError("Invalid value for `clinician`, must not be `None`")  # noqa: E501

        self._clinician = clinician

    @property
    def prior_authorization_id(self):
        """Gets the prior_authorization_id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        The Prior Authorization ID.              <div><p><strong style=\"border: 5% solid #584c7e;padding:1px;border-radius: 5%;background: #584c7e;color:white;\"> Conditional required</strong> required when there is an authorization for this claim              </p></div>  # noqa: E501

        :return: The prior_authorization_id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: str
        """
        return self._prior_authorization_id

    @prior_authorization_id.setter
    def prior_authorization_id(self, prior_authorization_id):
        """Sets the prior_authorization_id of this TpoDataDTOsClaimActivityDTO.

        The Prior Authorization ID.              <div><p><strong style=\"border: 5% solid #584c7e;padding:1px;border-radius: 5%;background: #584c7e;color:white;\"> Conditional required</strong> required when there is an authorization for this claim              </p></div>  # noqa: E501

        :param prior_authorization_id: The prior_authorization_id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: str
        """

        self._prior_authorization_id = prior_authorization_id

    @property
    def dispensed_activity_id(self):
        """Gets the dispensed_activity_id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        Dispensed Activity ID.               Represents the activity Id from the transaction we want to dispense.              <div><p><strong style=\"border: 5% solid #584c7e;padding:1px;border-radius: 5%;background: #584c7e;color:white;\"> Conditional required</strong> required when submission type equals “Prescription-Dispense”              </p></div>  # noqa: E501

        :return: The dispensed_activity_id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: str
        """
        return self._dispensed_activity_id

    @dispensed_activity_id.setter
    def dispensed_activity_id(self, dispensed_activity_id):
        """Sets the dispensed_activity_id of this TpoDataDTOsClaimActivityDTO.

        Dispensed Activity ID.               Represents the activity Id from the transaction we want to dispense.              <div><p><strong style=\"border: 5% solid #584c7e;padding:1px;border-radius: 5%;background: #584c7e;color:white;\"> Conditional required</strong> required when submission type equals “Prescription-Dispense”              </p></div>  # noqa: E501

        :param dispensed_activity_id: The dispensed_activity_id of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: str
        """

        self._dispensed_activity_id = dispensed_activity_id

    @property
    def observation(self):
        """Gets the observation of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        Activity Observation.  # noqa: E501

        :return: The observation of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: list[TpoDataDTOsSharedObservationDTO]
        """
        return self._observation

    @observation.setter
    def observation(self, observation):
        """Sets the observation of this TpoDataDTOsClaimActivityDTO.

        Activity Observation.  # noqa: E501

        :param observation: The observation of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: list[TpoDataDTOsSharedObservationDTO]
        """

        self._observation = observation

    @property
    def result(self):
        """Gets the result of this TpoDataDTOsClaimActivityDTO.  # noqa: E501

        Activity Result.  # noqa: E501

        :return: The result of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :rtype: list[TpoDataDTOsClaimActivityResultDTO]
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this TpoDataDTOsClaimActivityDTO.

        Activity Result.  # noqa: E501

        :param result: The result of this TpoDataDTOsClaimActivityDTO.  # noqa: E501
        :type: list[TpoDataDTOsClaimActivityResultDTO]
        """

        self._result = result

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataDTOsClaimActivityDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataDTOsClaimActivityDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
