# coding: utf-8

"""
    Transaction Management Bus (TMB) API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V3.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TpoDataDTOsLabLabRequestDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'header': 'TpoDataDTOsSharedHeaderDTO',
        'order': 'TpoDataDTOsLabOrderDTO'
    }

    attribute_map = {
        'header': 'Header',
        'order': 'Order'
    }

    def __init__(self, header=None, order=None):  # noqa: E501
        """TpoDataDTOsLabLabRequestDTO - a model defined in Swagger"""  # noqa: E501
        self._header = None
        self._order = None
        self.discriminator = None
        self.header = header
        self.order = order

    @property
    def header(self):
        """Gets the header of this TpoDataDTOsLabLabRequestDTO.  # noqa: E501


        :return: The header of this TpoDataDTOsLabLabRequestDTO.  # noqa: E501
        :rtype: TpoDataDTOsSharedHeaderDTO
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this TpoDataDTOsLabLabRequestDTO.


        :param header: The header of this TpoDataDTOsLabLabRequestDTO.  # noqa: E501
        :type: TpoDataDTOsSharedHeaderDTO
        """
        if header is None:
            raise ValueError("Invalid value for `header`, must not be `None`")  # noqa: E501

        self._header = header

    @property
    def order(self):
        """Gets the order of this TpoDataDTOsLabLabRequestDTO.  # noqa: E501


        :return: The order of this TpoDataDTOsLabLabRequestDTO.  # noqa: E501
        :rtype: TpoDataDTOsLabOrderDTO
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this TpoDataDTOsLabLabRequestDTO.


        :param order: The order of this TpoDataDTOsLabLabRequestDTO.  # noqa: E501
        :type: TpoDataDTOsLabOrderDTO
        """
        if order is None:
            raise ValueError("Invalid value for `order`, must not be `None`")  # noqa: E501

        self._order = order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpoDataDTOsLabLabRequestDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpoDataDTOsLabLabRequestDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
